name: Deploy Project
# on: [push, workflow_dispatch]
on: [workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: install NodeJs
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
            - name: install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Test Code
              run: npm run test
            - name: Build Code
              run: npm run build
            - name: Deploy Code
              run: echo "Deplying code..."
    