name: 'Get & cache Dependencies'
description: 'Get code and cache dependencies'
inputs:
  caching:
    description: 'Enable caching'
    required: false
    default: 'true'
outputs:
  used-cache:
    value: ${{ steps.install.outputs.cache }}
    description: 'Cache used status'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }}
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      id: install
      run: | 
        npm ci
        echo "cache=${{ inputs.caching }}" >> $GITHUB_OUTPUTS
      shell: bash
