name: demo1
on: 
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]
  push:
    branches: [main, develop]
  workflow_dispatch:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: output event details
              run: echo "${{ toJson(github) }}"
            - name: Checkout code
              uses: actions/checkout@v4
            - name: install NodeJs
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
            - name: install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Test Code
              run: npm run test
            - name: Build Code
              run: npm run build
            - name: Deploy Code
              run: echo "Deplying code..."
    