name: Output information
on: workflow_dispatch

jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: output github context
              run: echo "${{ toJson(github) }}"
            - name: install NodeJs
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
            - name: install dependencies
              run: npm ci
            - name: Output information
              run: |
                  echo "Node.js version:" $(node -v)
                  echo "npm version:" $(npm -v)
                  echo "Project directory:" $(pwd)
                  echo "Project files:" $(ls -al)