name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
            version:
                required: true
                type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying to ${{ inputs.environment }} with version ${{ inputs.version }}"